name: practice_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  flutter_bloc: any
  auto_route: ^6.1.0
  equatable: any  
  dio: any
  firebase_core: any 
  cloud_firestore: any

  get_it: any
  flutter_svg: any 
  cupertino_icons: any
  logger: any 

  flutter_dotenv: any 

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any 
  auto_route_generator: ^6.1.0
  analyzer: ^5.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - .env
