name: practice_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  flutter_bloc: any
  auto_route: ^6.1.0
  equatable: any  
  dio: any
  retrofit: any
  firebase_core: any 
  firebase_auth: any
  get_it: any
  flutter_svg: any 
  cupertino_icons: any
  logger: any 
  dartz: ^0.10.1
  flashy_flushbar: any
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.0.15
  local_auth: any
  json_annotation: any
  flutter_dotenv: any
  fl_chart: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any 
  auto_route_generator: ^6.1.0
  analyzer: ^5.9.0
  flutter_native_splash: any
  isar_generator: ^3.1.0
  json_serializable: any
  retrofit_generator: any


flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/pngs/
    - .env

flutter_native_splash:
  color: "#000000"  # Background color
  image: assets/pngs/icon.png
  android: true
  ios: true
  web: true



